
version: '3.1'

services:
  mongodb:
    container_name: db-blog
    image: mongo:latest
    restart: always
    environment:
        - MONGO_DB_ROOT_USERNAME=${MONGO_DB_ROOT_USERNAME}
        - MONGO_DB_ROOT_PASSWORD=${MONGO_DB_ROOT_PASSWORD}
        - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
        - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
        - MONGO_DB_NAME=${MONGO_DB_NAME}
    ports:
      - ${MONGO_DB_LOCAL_PORT}:${MONGO_DB_DOCKER_PORT}
    volumes:
    - ./mongo-entrypoint/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    command: [--auth]
